<?xml version="1.0" encoding="utf-8"?><Database Name="GamerTagDB" Class="GamerTagDBLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\GamerTagDB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GamerTagDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="live" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="psn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="steam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="wiiu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="games" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>